/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmarecekAmbulanceWlList {
    }
}
declare global {
    interface HTMLXmarecekAmbulanceWlListElement extends Components.XmarecekAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXmarecekAmbulanceWlListElement: {
        prototype: HTMLXmarecekAmbulanceWlListElement;
        new (): HTMLXmarecekAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xmarecek-ambulance-wl-list": HTMLXmarecekAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XmarecekAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xmarecek-ambulance-wl-list": XmarecekAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmarecek-ambulance-wl-list": LocalJSX.IntrinsicElements["xmarecek-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXmarecekAmbulanceWlListElement>;
        }
    }
}
